# Memahami Perbedaan Rata-rata Antar Kelompok

Meneliti dan memahami bagaimana suatu kelompok dapat berbeda jika dibandingkan dengan kelompok lainnya, merupakan salah satu hal penting dan sering menjadi tujuan penelitian pada ranah ilmu sosial, termasuk psikologi. Pemahaman ini sangat diperlukan ketika peneliti ingin mengetahui **efektivitas** dari intervensi atau manipulasi yang dilakukan. Misalnya, seorang dosen ingin mengetahui apakah penjelasan materi dengan pemberian video pembelajaran dapat meningkatkan pemahaman mahasiswa pada mata kuliah statistik. Untuk mengujinya, dosen tersebut melakukan penelitian eksperimental di mana satu kelompok/kelas mahasiswa mendapatkan video pembelajaran, sedangkan kelompok/kelas lainnya tidak.

Kelompok yang mendapatkan video pembelajaran disebut dengan kelompok eksperimen/*treatment group* (KE). KE adalah sekelompok partisipan penelitian yang mendapatkan perlakuan atau intervensi tertentu yang diharapkan dapat menyebabkan terjadinya perbedaan hasil (misalnya, penurunan atau peningkatan skor). Pada contoh sebelumnya, video pembelajaran adalah intervensi yang diberikan untuk meningkatkan skor pemahaman mahasiswa. Sementara itu, kelompok yang tidak mendapatkan perlakuan atau intervensi, disebut dengan kelompok kontrol/*control group* (KK).

Desain penelitian yang melibatkan KE dan KK ini umumnya ditemui pada *setting* **eksperimental**, di mana peneliti dengan sengaja membagi kelompok dan memberikan perlakuan yang berbeda, seperti pada uji coba klinis. Akan tetapi, dalam konteks ilmu sosial, sangat memungkinkan kelompok tertentu mendapatkan perlakukan atau mengalami hal yang berbeda, dan seolah menjadi “*treatment”* yang terjadi secara alami/natural. Misalnya, adanya pembentukan kelompok karena perbedaan kelas di sekolah, kelompok pekerja, perbedaan generasi, dan sebagainya.

Adanya perbedaan kelompok tersebut sangat memungkinkan untuk menimbulkan perbedaan karakteristik, perilaku atau performa antar kelompok. Contohnya, variabel “*risk-taking behavior”* pada karyawan. Apakah perilaku tersebut akan sama antara karyawan yang baru masuk perusahaan (awal karier) dengan mereka yang sudah mendekati masa pensiun (akhir karier)? Kedua kelompok tersebut akan memiliki perbedaan pemikiran, keterikatan terhadap organisasi dan perilaku kerja. Jika tidak ada perbedaan perlakuan yang dengan sengaja diciptakan atau dimanipulasi oleh peneliti, peneliti umumnya membedakan kedua kelompok dengan menyebutkan Kelompok 1 vs Kelompok 2 atau secara spesifik menyebutkan hal yang membedakan kedua kelompok (misal: kelompok awal karier vs kelompok akhir karier).
