# Analisis Perbedaan Rata-rata Antar Kelompok vs. Dalam Kelompok

Secara statistik, uji beda dilakukan untuk mengetahui apakah terdapat perbedaan **antar kelompok (*between groups*)** atau perbedaan **dalam kelompok (*within groups*)**. Perbedaan antar kelompok dilakukan untuk mengetahui apakah dua kelompok *independent* (kelompok yang tidak sama) memiliki perbedaan satu sama lain dalam hal yang sedang diteliti (*dependent variable*).

Uji beda ini umum digunakan untuk mengukur seberapa efektif sebuah *treatment* atau intervensi yang diberikan. Misalnya, peneliti ingin mengetahui apakah intervensi yang dirancang efektif dalam menurunkan tingkat kecemasan mahasiswa terhadap pelajaran statistik. Satu kelompok akan mendapatkan *treatment* penurunan kecemasan (KE), sementara kelompok lain sebagai kelompok pembanding, yaitu mereka yang tidak mendapatkan *treatment* (KK). Kedua kelompok kemudian diukur tingkat kecemasannya setelah mendapatkan *treatment* (sebagai *outcome*), untuk selanjutnya dibandingkan apakah ada perbedaan tingkat kecemasan antara kedua kelompok.

Perbedaan dalam kelompok dapat digunakan untuk mengetahui efektivitas dari sebuah program intervensi, hanya saja tidak membandingkan dua kelompok yang berbeda. Melainkan, perbedaan dilihat pada kelompok yang sama namun dalam dua kondisi atau waktu yang berbeda. Misalnya, peneliti ingin mengetahui apakah program olah raga yang dirancang efektif dalam menurunkan berat badan dengan membandingkan BMI partisipan antara sebelum (waktu 1) dengan sesudah (waktu 2) mengikuti program olah raga.

Pada kedua jenis uji beda yang telah dibahas, hal yang dibandingkan adalah perbedaan rata-rata (*mean differences)* variabel yang diteliti. Pada uji beda antar kelompok, hal yang dilihat adalah perbedaan rata-rata antara KE dan KK (perbedaan rata-rata skor kecemasan antara kelompok yang mendapatkan dan tidak mendapatkan intervensi kecemasan). Sementara itu, ketika melakukan uji beda dalam kelompok, hal yang dibandingkan adalah perbedaan rata-rata pada dua waktu pengukuran yang berbeda (perbedaan rata-rata BMI antara sebelum dan sesudah mengikuti program).

Selain perbedaan rata-rata, hal yang juga perlu diperhatikan adalah simpangan baku dari rata-rata yang dibandingkan (standar deviasi*/SD)* dan jumlah partisipan pada kedua kelompok. Jika ketiga hal tersebut diketahui, maka uji beda antar dan dalam kelompok dapat dilakukan dengan penghitungan *t-test*, untuk mengetahui apakah perbedaan rata-rata tersebut signifikan secara statistik. Terdapat dua jenis uji *t-test* yang akan dibahas lebih lanjut, yaitu ***independent sample t-test*** (uji beda antar kelompok berbeda) dan ***paired sample t-test*** (uji beda dalam kelompok)*.*
