project:
  type: book
  output-dir: docs

site-url: https://yarsi-psikologi.github.io/bukustat/
  
book:
  title: "Statistik untuk Psikologi dan Ilmu Sosial"
  subtitle: "Buku Panduan Praktis untuk Mahasiswa dan Peneliti Muda"
  reader-mode: true
  author: 
    - "Sunu Bagaskara"
    - "Entin Nurhayati"
    - "Sari Zakiah Akmal"
    - "Titi Sahidah Fitriana"
    - "Aswin Januarsjaf"
  language: id
  date: "8/30/2025"
  date-format: "D MMMM YYYY"
  sidebar:
    style: docked
    search: true
    collapse-level: 1
    logo: coverv3.jpg
          
  page-footer:
    left: |
      Statistik untuk Psikologi & Ilmu Sosial
    right: |
      Buku ini dicetak menggunakan <a href="https://quarto.org/">Quarto</a>.
  cover-image: coverv3.jpg
  favicon: coverv3.jpg
  chapters:
    - index.qmd
    - about.qmd

    - part: 1_pengantar.qmd
      chapters:
        - 1_1_sejarah.qmd
        - 1_2_stat_psiko.qmd
        - 1_3_jenis_stat.qmd
        - 1_latihan.qmd
        
    - part: 2_persiapan.qmd
      chapters: 
        - 2_1_jenis_data.qmd
        - 2_2_cleaning.qmd
        - 2_3_akuntabilitas.qmd
        - 2_latihan.qmd
      
    - part: 3_deskriptif.qmd
      chapters: 
        - 3_1_sentral.qmd
        - 3_2_dispersi.qmd
        - 3_3_distribusi.qmd
        - 3_latihan.qmd
      
    - part: 4_inferensial.qmd
      chapters: 
        - 4_1_parametrik.qmd
        - 4_2_power.qmd
        - 4_3_hipotesis.qmd
        - 4_4_signifikansi.qmd
        - 4_5_confidence.qmd
        - 4_6_effect_size.qmd
        - 4_latihan.qmd

    - part: 5_t-test.qmd
      chapters: 
        - 5_1_perbedaan.qmd
        - 5_2_between_within.qmd
        - 5_3_independent_ttest.qmd
        - 5_4_paired_ttest.qmd
        - 5_latihan.qmd
      
    - part: 6_anova.qmd
      chapters: 
        - 6_1_tujuan_anova.qmd
        - 6_2_prinsip_anova.qmd
        - 6_3_jenis_anova.qmd
        - 6_4_anova_nonpar.qmd
        - 6_latihan.qmd
      
    - part: 7_korelasi.qmd
      chapters: 
        - 7_1_karakteristik_korelasi.qmd
        - 7_2_asumsi_korelasi.qmd
        - 7_latihan.qmd
    
    - part: 8_regresi.qmd
      chapters: 
        - 8_1_prinsip_regresi.qmd
        - 8_2_regresi_sederhana.qmd
        - 8_3_regresi_majemuk.qmd
        - 8_4_regresi_hierarkis.qmd
        - 8_latihan.qmd
    
    - glosarium.qmd
    - references.qmd

bibliography: references.bib
bibliographystyle: apa
csl: apa7id.csl

lang: id
language: id.yml

crossref: 
  sec-prefix: "Bab"
  fig-prefix: "Gambar"
  tbl-prefix: "Tabel"
  eq-prefix: "Persamaan"
  
format:
  html:
    theme:
      - united
      - brand
    css: styles2.scss
    code-link: true
    author-meta: "Sunu Bagaskara, Entin Nurhayati, Sari Zakiah Akmal, Titi Sahidah Fitriana, & Aswin Januarsjaf"
    breadcrumb: true
    title-block-banner: banners.png
  pdf:
    documentclass: book
    pdf-engine: lualatex
    lof: true     # aktifkan List of Figures
    lot: true     # aktifkan List of Tables (opsional)
    classoption: [openany]
    papersize: a4
    mainfont: "Ubuntu light"
    fontsize: 10pt
    mainfontoptions: 
      - UprightFont=Ubuntu light      
      - ItalicFont=Ubuntu italic
      - BoldFont=Ubuntu bold
      - BoldItalicFont=Ubuntu bold italic
    #sansfont: "Ubuntu Light"
    #monofont: "Ubuntu Light"
    geometry: 
      - paperwidth=8.0000000000000in
      - paperheight=10.000000000000in
      - left=1.25in
      - textwidth= 5.25in
      - top=1.00in
      - textheight=8.25in
    include-in-header: "header.tex"
    include-after-body: 
      text: |
        \printindex
    toc: true
    toc-title: "Daftar Isi"
    linkcolor: blue
    urlcolor: blue
    citecolor: blue

editor: visual